description: >
  This is a sample executor using Docker and MetsaDeploy.
docker:
  - image: '<<parameters.docker_image>>:<<parameters.tag>>'
parameters:
  docker_image:
    type: string
    default: "cimg/node"
    description: "Image for MetaDeploy"
  tag:
    default: lts
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/r/cimg/node/tags
    type: string
